name: dird-odoo-contact
namespace: quintana
version: 0.0.2
author: Sylvain Boily
display_name: Odoo contacts
plugin_format_version: 1
min_wazo_version: 20.10
tags:
  - community
  - contact
homepage: https://github.com/alexis-via/xivo-dird-plugin-backend-odoo
