name: dird-odoo-contact
namespace: quintana
version: 0.0.1
author: Sylvain Boily
display_name: Odoo contacts
plugin_format_version: 1
min_wazo_version: 17.17
tags:
  - beta
  - application
homepage: https://github.com/alexis-via/xivo-dird-plugin-backend-odoo
